### ISSUE TITLE
Add options for command with space

### ISSUE THREAD

**Issue by micron10** [diggerwoo/jsh#3]
Hi @diggerwoo 

your jail look very good i try to add this but not work , do have options to add : 

in group.jailed.conf

alias show config "cat /etc/config"
alias show interface ips  "ip address list"

show config
show interface  ips 

and after that in man.conf : 

show 
   config "List config"
   interface ips "List interface ips"

now problem is set for all show command same info like : 

command 
  show  - "Shows various information"
  interface show - "Shows various information"

**Comment by diggerwoo** [comment]
The keyword and parameters of jsh cannot support spaces. For your scenario, the keyword "show" must map to a existing executable. I think what you need is a customized "show" command just like router gears.

I would recommend to add a "show" executable:

```sh
touch /usr/local/bin/show
chmod a+x /usr/local/bin/show
```

then vi /usr/local/bin/show like below:

```sh
#!/bin/sh

if [ "$1" == "config" ]; then
    cat /etc/config
elif [ "$1" == "interface" -a "$2" == "ips" ]; then
    ip addr list
fi 
```

**Comment by diggerwoo** [comment]
@micron10 
I've updated jtrace.c as your requirement.
Hope this make the vim/sftp jailing more adaptive.
Thanks.
